In [1]:
import math
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from keras.models import Sequential
from keras.layers import Dense, LSTM
import matplotlib.pyplot as plt

Using TensorFlow backend.
C:\Users\EL FASHKA\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\EL FASHKA\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\EL FASHKA\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\EL FASHKA\anaconda3\lib\site-packages\tensorflow\python\fra

In [2]:
bitcoin = pd.read_csv('C:/Users/EL FASHKA/Desktop/FABB/BTC-EUR.csv', index_col = 'Date', parse_dates = True )
bitcoin.head()

Open        High         Low       Close   Adj Close  \
Date                                                                     
2014-09-17  359.546204  361.468506  351.586884  355.957367  355.957367   
2014-09-18  355.588409  355.505402  319.789459  328.539368  328.539368   
2014-09-19  328.278503  330.936707  298.921021  307.761139  307.761139   
2014-09-20  307.665253  329.978180  303.931244  318.758972  318.758972   
2014-09-21  318.120514  321.504517  306.502197  310.632446  310.632446   

              Volume  
Date                  
2014-09-17  16389165  
2014-09-18  26691849  
2014-09-19  29560102  
2014-09-20  28736825  
2014-09-21  20702624

In [92]:
#bitcoin['Close'].plot()
#bitcoin.drop([ 'Volume'],1, inplace=True)
bitcoin.tail()

Close  prediction
Date                                
2019-08-06  10243.875977         NaN
2019-08-07  10658.732422         NaN
2019-08-08  10697.322266         NaN
2019-08-09  10516.327148         NaN
2019-08-10  10065.183594         NaN

In [60]:
predictions_d = bitcoin['2014-09':'2015-01']
s=len(predictions_d)
s

137

In [67]:
bitcoin['prediction'] = bitcoin[['Close']].shift(-s)
bitcoin.head(7)
#bitcoin.shape

Close  prediction
Date                              
2014-09-17  355.957367  200.735825
2014-09-18  328.539368  210.115540
2014-09-19  307.761139  198.418030
2014-09-20  318.758972  200.471008
2014-09-21  310.632446  189.285950
2014-09-22  312.958771  196.348068
2014-09-23  339.189758  201.196106

In [71]:
X = np.array(bitcoin.drop(['prediction'],1))
X=X[:len(bitcoin)- s]
X

array([[ 355.957367],
       [ 328.539368],
       [ 307.761139],
       ...,
       [3560.789307],
       [3502.470703],
       [3534.563477]])

In [72]:
y = np.array(bitcoin['prediction'])
y = y[:-s]
y

array([  200.735825,   210.11554 ,   198.41803 , ..., 10697.322266,
       10516.327148, 10065.183594])

In [74]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X,y, test_size=0.2)

In [75]:
pred_d_array = np.array(bitcoin.drop(['prediction'],1))[-s:]
print(pred_d_array)

[[ 3631.979492]
 [ 3623.731201]
 [ 3652.061523]
 [ 3659.444824]
 [ 3657.865967]
 [ 3710.858154]
 [ 4354.895508]
 [ 4422.508301]
 [ 4386.38623 ]
 [ 4488.186523]
 [ 4508.803223]
 [ 4634.541016]
 [ 4699.305664]
 [ 4619.98877 ]
 [ 4722.057617]
 [ 4497.265137]
 [ 4500.679199]
 [ 4506.911621]
 [ 4571.382813]
 [ 4482.450195]
 [ 4639.527832]
 [ 4649.068359]
 [ 4715.563477]
 [ 4716.388672]
 [ 4746.688477]
 [ 4726.600586]
 [ 4795.597656]
 [ 4964.707031]
 [ 4899.657227]
 [ 4678.542969]
 [ 4732.407715]
 [ 4722.169434]
 [ 4740.140625]
 [ 4690.791992]
 [ 4771.259277]
 [ 4823.619629]
 [ 4927.245605]
 [ 5147.044434]
 [ 5203.150879]
 [ 5181.746094]
 [ 5130.174805]
 [ 5209.499023]
 [ 5342.549805]
 [ 5503.882324]
 [ 5678.451172]
 [ 6413.687988]
 [ 6205.382813]
 [ 6958.033203]
 [ 7134.912598]
 [ 7321.372559]
 [ 7057.222656]
 [ 6578.515137]
 [ 6513.402832]
 [ 7342.637695]
 [ 7142.94043 ]
 [ 7131.446777]
 [ 6884.596191]
 [ 7047.166992]
 [ 7128.090332]
 [ 7185.599121]
 [ 7737.375977]
 [ 7866.871094]
 [ 7808.

In [77]:
from sklearn.svm import SVR
svr_rbf = SVR(kernel = 'rbf', C= 1e3, gamma=0.00001)
svr_rbf .fit(x_train, y_train)

SVR(C=1000.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma=1e-05,
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [78]:
svr_rbf_confidence = svr_rbf .score(x_test, y_test)
print("svr_rbf_accuracy:", svr_rbf_confidence )

svr_rbf_accuracy: 0.8493208085838859


In [79]:
svm_pred = svr_rbf.predict(x_test)
print(svm_pred)
print()

print(y_test)

[2572.47307502  511.63011533  780.32628332 6538.48773854 3470.50922192
 9635.05123821  814.27061354 7767.42235576  842.52149006 2400.33509104
 2409.97808989  803.30402713  243.69064293  570.12974249  794.14849
 1346.95957026 2465.65172263  234.32551651  267.4948077  8010.98275092
  265.17082941 6916.30013927 5952.51321661 5639.23635809 3500.77796185
 6093.11644266  884.82849986  252.69387335  796.09042001  622.43063748
 7262.37864108  274.79136993 7932.78202737 5290.65213865  319.89409883
  247.55161302  245.53600348  947.71123816  599.83126998  266.33871807
  822.45137665 7920.10013631  565.32228233 3480.75251711 5707.49184467
 2422.53182285  243.15008205 3439.74844746 6564.95335216 5722.53248475
  408.57405837 5460.37075371  861.04317275 6099.19198883 7783.09585712
  406.83506079  244.75033544 3178.17085651  328.73688814  572.96223415
 2468.18811019 7514.68477895  796.54662982 1068.2131873  5718.33908721
 7161.74490752 1376.67001272 5749.74082662 6546.37036938 8911.4284198
  296.5320

In [111]:
svm_pred = svr_rbf.predict(pred_d_array)
print(svm_pred)

[9658.47371253 9654.47902133 9650.08866331 9640.84589046 9643.08957108
 9497.84275706 6945.92832073 7048.16330707 6973.34905619 7278.08950908
 7366.24178892 7874.23089684 8007.68009238 7828.05493453 8024.11806615
 7316.34598462 7330.97907894 7357.98150793 7641.6113353  7254.48715983
 7888.81020119 7914.82690046 8021.0610437  8021.521469   8024.14971784
 8025.48936211 7974.54250433 7481.49108719 7712.58109618 7978.61890635
 8026.33237347 8024.15937091 8025.89222315 7997.38537113 8006.91304966
 7921.09132985 7620.19173587 6378.04515373 5829.35611539 6049.1843203
 6523.57796089 5762.17648519 4354.34311083 3507.7140192  3527.72709162
 5598.89978557 5281.46227413 5492.75264882 5558.68869586 5789.19715433
 5471.13450037 5702.0834693  5671.30390518 5792.59330704 5571.11850181
 5553.44404565 5587.1355192  5465.91186123 5548.44418246 5640.47706484
 5635.95241275 5710.52232577 5682.53096624 5661.26040557 5710.4360861
 5602.23664697 5601.05299534 5692.27614039 5779.26764471 5637.38567144
 5483.47

In [112]:
print(bitcoin.tail(s))

                   Close  prediction
Date                                
2019-03-27   3631.979492         NaN
2019-03-28   3623.731201         NaN
2019-03-29   3652.061523         NaN
2019-03-30   3659.444824         NaN
2019-03-31   3657.865967         NaN
...                  ...         ...
2019-08-06  10243.875977         NaN
2019-08-07  10658.732422         NaN
2019-08-08  10697.322266         NaN
2019-08-09  10516.327148         NaN
2019-08-10  10065.183594         NaN

[137 rows x 2 columns]


In [15]:
x_train = []
y_train = []
for i in range(60, len(train_data)):
    x_train.append(train_data[i-60:i, 0])
    y_train.append(train_data[i, 0])
    if i <= 60:
        print(x_train)
        print(y_train)
        print()

[array([0.72659129, 0.71462973, 0.68929339, 0.68707744, 0.6802035 ,
       0.67247032, 0.64942906, 0.63191634, 0.61444884, 0.60569813,
       0.59787451, 0.60079141, 0.59773884, 0.60459016, 0.60373092,
       0.60662521, 0.60775579, 0.60356133, 0.60360656, 0.61193895,
       0.62157151, 0.63226682, 0.64286037, 0.65588468, 0.66858112,
       0.68429621, 0.6988355 , 0.68627473, 0.67429056, 0.66428491,
       0.65200678, 0.        , 0.64864895, 0.        , 0.64384398,
       0.        , 0.6454381 , 0.        , 0.65187111, 0.        ,
       0.67597513, 0.        , 0.70018089, 0.        , 0.71518372,
       0.        , 0.72572075, 0.        , 0.72903335, 0.        ,
       0.72533635, 0.        , 0.7149576 , 0.        , 0.70239683,
       0.        , 0.68944036, 0.        , 0.67780667, 0.        ])]
[0.6854946297343132]

